### ISSUE TITLE
Having Issues Writing a Server Config

### ISSUE THREAD

**Issue by aidanj5** [nspyre-org/nspyre#15]
Sorry, I don't know if this is the best place to put this, but I do not understand why something I am writing is not working.

I am trying to connect a simulated DAQ to the new instrument server. It worked fine on the old nspyre. Now, this is the result I get, followed by three different tracebacks.
![image](https://user-images.githubusercontent.com/47992941/96770662-7e014780-1395-11eb-8f9f-2feb3b781df7.png)

I took the input I had in the old code, which is the picture shown below:
![image](https://user-images.githubusercontent.com/47992941/96770806-ab4df580-1395-11eb-990b-7f196d406eae.png)

I transferred it to a new config file set up as default to my instrument server, and I believe I put it in the correct syntax.
![image](https://user-images.githubusercontent.com/47992941/96771281-4c3cb080-1396-11eb-8865-68ed450ef13f.png)

The other simulated instruments load properly. The only informative error message I am able to get is the following: 
![image](https://user-images.githubusercontent.com/47992941/96771105-17305e00-1396-11eb-807c-2d5d6d3581c1.png)

However, I don't understand this. What am I doing wrong?

Note: I am starting the inserv with the daq instrument commented out. I then uncomment it, reread the config, and type ">dev daq" to connect the device. If I have it uncommented while I start the server, I am not able to keyboard interrupt, so I have to restart my terminal.

**Comment by jacobfeder** [comment]
Hi @aidanj5 ,
I suspect this may have something to do with outdated values in mongodb from the previous version of nspyre conflicting with the new version. Can you try rerunning `nspyre-mongodb` and see if that changes anything?

**Comment by aidanj5** [comment]
After a computer restart for the night, I reran nspyre-mongodb in one command prompt. Then "lantz-sims fungen tcp" for the fake instrument in another. Then nspyre-inserv in another. 

I make sure mongo is working, after seeing this prompt : 
![image](https://user-images.githubusercontent.com/47992941/96901177-c711d400-1447-11eb-95f2-83ce4ebe4bc2.png)

I get a bunch of these debug messages from PyVISA, I'm unsure what this tells me. 
![image](https://user-images.githubusercontent.com/47992941/96901358-02140780-1448-11eb-88fb-341e2768dd5c.png)

Then I get the errors still.
![image](https://user-images.githubusercontent.com/47992941/96901407-10622380-1448-11eb-855c-2b91ea430837.png)

Am I doing something wrong with running mongodb?

**Comment by aidanj5** [comment]
I just realized, the mongo server version is 4.2.10, despite having 4.4 on my computer. I am going to try to reinstall mongodb.

**Comment by jacobfeder** [comment]
Everything looks ok to me (except for the error of course). The mongo shell version doesn't particularly matter. I can take a closer look with you.

**Comment by mtsolmn** [comment]
hi @aidanj5, try using the following in the config file and let us know the error you get:
```
...
daq:
  lantz_class: ni.simple_daq.Read_DAQ
  args: [{'Dev1'}]
  kwargs:
```

I'm not sure if that will work, but I'm interested in the error you get if it doesn't. Thanks.

**Comment by jacobfeder** [comment]
@mtsolmn - @aidanj5 and I traced it a bit this afternoon and it seems to be an issue inside the DAQ lantz driver. I suspect something resulting from the transition to new lantz. We fixed the issue, but then immediately ran into something else. I think there may be several more changes required to get it up and running on new lantz. I've filed a report in lantz-drivers:
https://github.com/lantzproject/lantz-drivers/issues/9

**Comment by aidanj5** [comment]
Just to be clear, I tried your suggestion @mtsolmn, and there is no change. I still have the same errors. The traceback shows that the error occurs when calling the lantz_class. @jacobfeder and I found there are problems with the initialization of the DAQ driver, and so this result is expected. Still, thank you for the suggestion!

**Comment by mtsolmn** [comment]
yes, thanks for the update both of you. I just wanted to confirm that this was an issue with the lantz driver and not something that needed to be addressed on the nspyre side. I'll leave this open for now, but maybe we close this soon.

I will also mention that there is a relatively new python API from National Instruments called ni-daqmx that is feature complete -- everything you can do in LabView with their DAQs you can now do through python -- until pydaqmx. It's also the official and supported python API now. We are trying to get everyone internally to use it going forward. Although there is no lantz driver for it, we have documentation for it available here: https://nspyre.readthedocs.io/en/develop/guides/ni-daqmx.html
